config/routes.rb
Rails.application.routes.draw do
   namespace :usefull_attachment do
     resources :links do
  		get "download", :on => :member
  	end
  end
end

app/controllers/usefull_attachment/links_controller.rb
module UsefullAttachment
  class LinksController < ApplicationController
    def index
      @search = Link.search(params[:search])
      @attachments = @search.paginate(:page => params[:page])
    end
    
    def new
      @attachment = Link.new
      #UserSession.log("Admin::AttachmentController#new params=#{params[:admin_attachment].inspect}, @attachment=#{@attachment.inspect}")
    end
    
    def create
      ##UserSession.log("Admin::AttachmentController#create params=#{params[:admin_attachment].inspect}")
      user = current_user ? {:created_by => current_user.id, :updated_by => current_user.id} : {}
      Attachment.create(params[:usefull_attachment_attachment].deep_merge!(user)) if params[:usefull_attachment_attachment].present?
      Avatar.create(params[:usefull_attachment_avatar].deep_merge!(user)) if params[:usefull_attachment_avatar].present?
      Link.create(params[:usefull_attachment_link].deep_merge!(user)) if params[:usefull_attachment_link].present?
      redirect_to :action => "index", :notice => t("created")
    rescue => e
      flash[:alert] = t("not_created", :message => e.message)
      redirect_to :back
    end

    def download
      @attachment = Link.find(params[:id])
      respond_to do |format|
        format.html do
          raise FileMissing.new(:file => @attachment.link.path) unless File.exist?(@attachment.link.path)
          send_file @attachment.link.path, :type => @attachment.link_content_type
        end
      end
    rescue => e
      flash[:alert] = t("not_downloaded", :message => e.message)
      redirect_to :back
    end

    def destroy
      @attachment = Link.find(params[:id])
      @attachment.destroy

      respond_to do |format|
        format.html do
          redirect_to :back, :notice => t("deleted")
        end
        format.xml  { head :ok }
      end
      
    rescue => e
      flash[:alert] = t("not_deleted", :message => e.message)
      redirect_to :back
    end

  end



end

app/views/usefull_attachment/links/index.html.erb
<%= filter_for @search, :html => {:class => 'usefull_filter_container span-24'}, :url => usefull_attachment_links_path do |f| %>
  <%= f.text_field :attachmentable_type %>
  <%= f.text_field :attachmentable_id %>
  <%= f.text_field :type %>
  <%#= f.text_field :typology %>
  <%= f.text_field :link_content_type %>
  <%= f.text_field :link_file_name %>
  <div class="span-22">
  <%= f.submit %>
<% end %>

<%=table_for(@attachments,@search) do |t| %>
  <% t.monitor %>
	<% t.download :url => Proc.new {|object| download_usefull_attachment_link_path(object)} %>
  <% t.destroy :url => Proc.new {|object| usefull_attachment_link_path(object)}, :link_options => {:confirm => 'Are you sure?', :method => :delete} %>
  <% t.col :id %>
  <% t.col :attachmentable_type %>
  <% t.col :attachmentable_id %>
  <% t.col :type %>
  <% t.col :typology %>
  <% t.col :description %>
  <% t.col :link_file_name %>
  <% t.col :link_file_size %>
  <% t.col :updated_at, :data_type => :DateTime %>
  <% t.col :link_content_type %>
  <% t.col "createdby_displayname" %>
  <% t.col "updatedby_displayname" %>
<% end %>

<%= link_to "New", new_usefull_attachment_link_path %>

app/views/usefull_attachment/links/new.html.erb
<%= form_for @attachment, :url => usefull_attachment_links_path, :html => { :multipart => true } do |form| %>
	Parent Class<%= form.text_field :attachmentable_type %>
	Type<%= form.text_field :type %>
	Description <%= form.text_field :description %>
  file <%= form.file_field :link %>
  Typology <%= form.text_field :typology %>
  <%= form.submit %>
<% end %>